name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm run build
      - name: Debug Git Worktrees
        run: git worktree list
      - name: Clean Worktrees
        run: |
          git worktree prune
          rm -rf .git/worktrees/github-pages-deploy-action-temp-deployment-folder || true
      - uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages
          folder: dist
          clean: true
          create-orphan: true
